### ISSUE TITLE
Swift 3 Support

### ISSUE THREAD

**Issue by surayashivji** [svenbacia/iTunesSearchAPI#10]
Will Swift 3 support be added? I noticed it's a requirement on the README, but when I install it via Cocoapods, I get a lot of Swift 3 errors. I've attached a screenshot for reference. 

<img width="260" alt="screen shot 2016-10-10 at 5 33 14 pm" src="https://cloud.githubusercontent.com/assets/12003060/19255142/a2ca71ea-8f0f-11e6-967e-7cbcd8716d6f.png">

Thank you for the fantastic wrapper!

**Comment by svenbacia** [comment]
Oh sorry, I forget to update the pod.

**Comment by surayashivji** [comment]
Should I do a pod update?

**Comment by svenbacia** [comment]
I'm currently working on it :)

**Comment by surayashivji** [comment]
Btw-- I met you at WWDC!

**Comment by svenbacia** [comment]
The pod should work now. Please let me know if there a further issues.

oh, thats awesome!
